DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS agents;
CREATE TABLE IF NOT EXISTS agents (
    id INTEGER PRIMARY KEY,
    token TEXT NOT NULL UNIQUE,
    wallet REAL DEFAULT 0
);

DROP TABLE IF EXISTS publishers;
CREATE TABLE IF NOT EXISTS publishers (
    id INTEGER PRIMARY KEY,
    token TEXT NOT NULL UNIQUE,
    wallet REAL DEFAULT 0
);
